---
title: "Lista do Módulo 2"
author: "Vinicius de Carvalho Zanini"
output: 
  html_document:
    highlight: tango
    include:
      after_body: psbfix.html
---

### Exercício 1

>Gere sinais sintéticos que simulem a forma de onda do ciclo respiratório, de acordo a faixa etária:
do nascimento a 6 semanas: 30 a 40 respirações por minuto;
6 meses: 25 a 40 respirações por minuto;
3 anos: 20 a 30 respirações por minuto;
6 anos: 18 a 25 respirações por minuto;
10 anos: 17 a 23 respirações por minuto;
Adultos: 12 a 18 respirações por minuto;
Idosos (≥ 65 anos): 12 a 28 respirações por minuto;
Idosos (≥ 80 anos): 10 a 30 respirações por minuto.

```{R}
tf <- 60 #tempo em segundos
dt <- 0.001 #intervalo entre amostras em segundos

t <- seq(from = 0, to = tf, by = dt ) # gera uma sequência (vetor tempo em segundos), para
# mais informações digite ?seq

fn <- 35 # frequência respiratória de um recém nascido
yn <- sin(2*pi*t*fn)
dfn <- data.frame(time=t, yn)

f6m <- 30 # frequência respiratória de uma criança de 6 meses
y6m <- sin(2*pi*t*f6m)
df6m <- data.frame(time=t, y6m)

f3A <- 23 # frequência respiratória de uma criança de 3 anos
y3A <- sin(2*pi*t*f3A)
df3A <- data.frame(time=t, y3A)

f6A <- 23 # frequência respiratória de uma criança de 6 anos
y6A <- sin(2*pi*t*f6A)
df6A <- data.frame(time=t, y6A)

f10A <- 23 # frequência respiratória de uma criança de 10 anos
y10A <- sin(2*pi*t*f10A)
df10A <- data.frame(time=t, y10A)

fA <- 23 # frequência respiratória de um adulto
yA <- sin(2*pi*t*fA)
dfA <- data.frame(time=t, yA)

fI <- 23 # frequência respiratória de uma idoso >= 65
yI <- sin(2*pi*t*fI)
dfI <- data.frame(time=t, yI)

fMI <- 23 # frequência respiratória de um idoso >= 85
yMI <- sin(2*pi*t*fMI)
dfMI <- data.frame(time=t, yMI)
```
### Exercício 2

> Utilize a bliblioteca dygraph para plotar um gráfico para cada um dos sinais 
simulados na questão 1. Adicione legendas para os eixos x e y de cada gráfico.

```{R}
library(dygraphs)
library(ggplot2)

tf <- 60 #tempo em segundos
dt <- 0.001 #intervalo entre amostras em segundos

t <- seq(from = 0, to = tf, by = dt ) # gera uma sequência (vetor tempo em segundos), para
# mais informações digite ?seq

fn <- 35 # frequência respiratória de um recém nascido
yn <- sin(2*pi*t*fn)
dfn <- data.frame(time=t, yn)

f6m <- 30 # frequência respiratória de uma criança de 6 meses
y6m <- sin(2*pi*t*f6m)
df6m <- data.frame(time=t, y6m)

f3A <- 23 # frequência respiratória de uma criança de 3 anos
y3A <- sin(2*pi*t*f3A)
df3A <- data.frame(time=t, y3A)

f6A <- 23 # frequência respiratória de uma criança de 6 anos
y6A <- sin(2*pi*t*f6A)
df6A <- data.frame(time=t, y6A)

f10A <- 23 # frequência respiratória de uma criança de 10 anos
y10A <- sin(2*pi*t*f10A)
df10A <- data.frame(time=t, y10A)

fA <- 23 # frequência respiratória de um adulto
yA <- sin(2*pi*t*fA)
dfA <- data.frame(time=t, yA)

fI <- 23 # frequência respiratória de uma idoso >= 65
yI <- sin(2*pi*t*fI)
dfI <- data.frame(time=t, yI)

fMI <- 23 # frequência respiratória de um idoso >= 85
yMI <- sin(2*pi*t*fMI)
dfMI <- data.frame(time=t, yMI)

tWindow <- c(10, 11)

dygraph(dfn, group = "G1")%>% dyRangeSelector(dateWindow = tWindow)%>% dyAxis("x", label = "tempo(s)")%>% dyAxis("y", label = "amplitude")

dygraph(df6m, group = "G1")%>% dyRangeSelector(dateWindow = tWindow)%>% dyAxis("x", label = "tempo(s)")%>% dyAxis("y", label = "amplitude")

dygraph(df3A, group = "G1")%>% dyRangeSelector(dateWindow = tWindow)%>% dyAxis("x", label = "tempo(s)")%>% dyAxis("y", label = "amplitude")

dygraph(df6A, group = "G1")%>% dyRangeSelector(dateWindow = tWindow)%>% dyAxis("x", label = "tempo(s)")%>% dyAxis("y", label = "amplitude")

dygraph(df10A, group = "G1")%>% dyRangeSelector(dateWindow = tWindow)%>% dyAxis("x", label = "tempo(s)")%>% dyAxis("y", label = "amplitude")

dygraph(dfA, group = "G1")%>% dyRangeSelector(dateWindow = tWindow)%>% dyAxis("x", label = "tempo(s)")%>% dyAxis("y", label = "amplitude") 

dygraph(dfI, group = "G1")%>% dyRangeSelector(dateWindow = tWindow)%>% dyAxis("x", label = "tempo(s)")%>% dyAxis("y", label = "amplitude")  

dygraph(dfMI, group = "G1")%>% dyRangeSelector(dateWindow = tWindow)%>% dyAxis("x", label = "tempo(s)")%>% dyAxis("y", label = "amplitude") 

```

### Exercício 3

>Utilize a função ggplot para plotar um gráfico para cada um dos sinais 
simulados na questão 1. Adicione legendas para os eixos x e y de cada gráfico.

```{R}

library(ggplot2)

tf <- 60 #tempo em segundos
dt <- 1 #intervalo entre amostras em segundos

t <- seq(from = 0, to = tf, by = dt ) # gera uma sequência (vetor tempo em segundos), para
# mais informações digite ?seq

fn <- 35 # frequência respiratória de um recém nascido
yn <- sin(2*pi*t*fn)
dfn <- data.frame(time=t, yn)

f6m <- 30 # frequência respiratória de uma criança de 6 meses
y6m <- sin(2*pi*t*f6m)
df6m <- data.frame(time=t, y6m)

f3A <- 23 # frequência respiratória de uma criança de 3 anos
y3A <- sin(2*pi*t*f3A)
df3A <- data.frame(time=t, y3A)

f6A <- 23 # frequência respiratória de uma criança de 6 anos
y6A <- sin(2*pi*t*f6A)
df6A <- data.frame(time=t, y6A)

f10A <- 23 # frequência respiratória de uma criança de 10 anos
y10A <- sin(2*pi*t*f10A)
df10A <- data.frame(time=t, y10A)

fA <- 23 # frequência respiratória de um adulto
yA <- sin(2*pi*t*fA)
dfA <- data.frame(time=t, yA)

fI <- 23 # frequência respiratória de uma idoso >= 65
yI <- sin(2*pi*t*fI)
dfI <- data.frame(time=t, yI)

fMI <- 23 # frequência respiratória de um idoso >= 85
yMI <- sin(2*pi*t*fMI)
dfMI <- data.frame(time=t, yMI)

ggplot(data=dfn, aes(t, yn)) + geom_point() + labs(x = "tempo (s)", y="amplitude(g)")

ggplot(data=df6m, aes(t, y6m)) + geom_point() + labs(x = "tempo (s)", y="amplitude (g)")

ggplot(data=df3A, aes(t, y3A)) + geom_point() + labs(x = "tempo (s)", y="amplitude (g)")

ggplot(data=df6A, aes(t, y6A)) + geom_point() + labs(x = "tempo (s)", y="amplitude (g)")

ggplot(data=df10A, aes(t, y10A)) + geom_point() + labs(x = "tempo (s)", y="amplitude (g)")

ggplot(data=dfA, aes(t, yA)) + geom_point() + labs(x = "tempo (s)", y="amplitude (g)")

ggplot(data=dfI, aes(t, yI)) + geom_point() + labs(x = "tempo (s)", y="amplitude (g)")

ggplot(data=dfMI, aes(t, yMI)) + geom_point() + labs(x = "tempo (s)", y="amplitude (g)")

```

### Exercício 4

>Escolha um sinal simulado na questão 1, e plote-o utilizando a função 
dyStemSeries. Por que há um intervalo temporal entre cada amostra?

```{R}
library(dygraphs)
ndow <- c(10, 11)

minuto <- 60 #tempo em segundos
segundo <- 1 #intervalo entre amostras em segundos

tempo <- seq(from = 0, to = minuto, by = segundo )

frequencia <- 35 # frequência respiratória de um recém nascido
cima <- sin(2*pi*tempo*frequencia)
dataframe <- data.frame(time=tempo, cima)

dygraph(dataframe, group = "G37")%>% dyStemSeries('cima')

#O graficco se apresenta dessa forma pois a função dyStemSeries apresenta cada ponto no momento que o sinal foi adquirido

```

### Exercício 5

> Explique a estrutura básica de um arquivo EDF 
(https://www.edfplus.info/specs/edf.html).


O EDF é montado por duas partes, o Header file onde ficam os primeiros 256
bytes, que informarão as metricas do arquivo, e os sinais que são o que será 
lido em si, cada um contendo seus proprios 256 bytes para identificação.
Elas seguem seu padrão pré-definido, correspondendo a amplitude e o deslocamento
(maximo e minimo) do sinal.O Header file é formado por ascii.

### Exercício 6

>Repita todos os exercícios apresentados neste módulo. Os comandos utilizados devem ser inseridos como resposta a esta questão.

```{R}
# Entrada da biblioteca
library(dygraphs)

tf <- 60 #tempo em segundos
dt <- 0.001 #intervalo entre amostras em segundos

t <- seq(from = 0, to = tf, by = dt ) # gera uma sequência (vetor tempo em segundos)

f1 <- 40 # frequência respiratória de um recém nascido
y1 <- sin(2*pi*t*f1)

f2 <- 23 # frequência respiratória de uma criança de 10 anos
y2 <- sin(2*pi*t*f2)

tWindow <- c(10, 11) # definição do intervalo de tempo (janela) para visualização de dados

df1 <- data.frame(time=t, y1) #criação de um dataframe para armazenamento dos dados
dygraph(df1, group = "G1")%>% dyRangeSelector(dateWindow = tWindow)

df2 <- data.frame(time=t, y2) #criação de um dataframe para armazenamento dos dados
dygraph(df2, group = "G1") %>%dyRangeSelector(dateWindow = tWindow)

tWindow <- c(10, 10.05) # definição do intervalo de tempo (janela) para visualização de dados

df2 <- data.frame(time=t, y2) #criação de um dataframe para armazenamento dos dados

#plotagem do gráfico do dataframe a cima
 dygraph(df2, group = "G1")  %>%dyRangeSelector(dateWindow = tWindow)%>%
  dyOptions(stemPlot=TRUE)
  

# Simulando a variação da SpO2 

library(dygraphs)

set.seed(123) # semente de aleatoriedade >>> controla o comportamento do gerador de números aleatórios

t <- seq(from = 0, to = 10, by = 0.001) # vetor de tempo em segundos

# Primeiro dia de monitoramento
y1 <- 97 + sin(2*pi*60*t)+sin(2*pi*30*t)+rnorm(length(t), mean = 0.3, sd = 0.1) # função simulando a variação da SpO2

# Segundo dia de monitoramento
y2 <- 97 + sin(2*pi*60*t+(pi/6))+sin(2*pi*30*t+(pi/6))+rnorm(length(t), mean = 0.5, sd = 0.1) # função simulando a variação da SpO2

dygraph(data.frame(t,y1,y2),xlab = "tempo (segundos)", ylab = "SpO2 (%)")%>%dyRangeSelector()%>%dyEvent("2.1","tempo fixo tk = 2.1", labelLoc = "bottom")

library(openxlsx)
library(ggplot2) 
library(edfReader)

# help(read.xlsx) # sempre que desejar obter help de uma função ou package digite help(nome_da_função) 

#abrindo um arquivo Excel
df1 <- read.xlsx("V16C1RCC92.xlsx", sheet = 1, skipEmptyRows = FALSE)

#Plotando um gráfico estático com a biblioteca ggplot2 (a mais completa do R)
qplot(df1$`[Time]`, df1$`[G1.X]`, data = df1) #gerando gráfico no formato rápido

qplot(df1$`[Time]`, df1$`[G1.X]`, geom=c("point", "line")) #gráfico de linhas e pontos

# Alterando o gráfico
p <- qplot(df1$`[Time]`, df1$`[G1.X]`, geom=c("point", "line"))
p <- p + labs(x = "tempo (s)", y="graus/s") # modificando unidades
print(p) # imprimindo o gráfico na tela

# gráficos mais versáteis
ggplot(data=df1, aes(x=df1$`[Time]`, y=df1$`[G1.X]`)) + geom_point()

ggplot(data=df1, aes(x=df1$`[Time]`, y=df1$`[G1.X]`)) + geom_line() #gráfico de linha

ggplot(data=df1, aes(x=df1$`[Time]`, y=df1$`[G1.X]`)) + geom_point() + geom_line() #gráfico de linha e ponto

library(dygraphs)

# Arquivo de texto para tabela
df2 <- read.table("V16C1RCC92.txt",header = TRUE, sep = "\t", dec = ".", skip = 1,quote="", comment.char="")

df2.1 <- data.frame(time=df2$X.Time., df2$X.G1.X.) #criação de um dataframe para armazenamento dos dados

dygraph(df2.1,main = "Velocidade angular (dps - degree per second)") %>% dyRangeSelector() %>%
  dyAxis("x", label = "tempo(s)")%>%
   dyAxis("y", label = "amplitude")

# Lendo o arquivo csv (com separador em ;)
df3 <- read.csv("V16C1RCC92.csv",header = TRUE, sep =  ";")
df3.1 <- data.frame(time=df3[[1]], amp=df3$X.A1.X.) #criação de um dataframe para armazenamento dos dados
 dygraph(df3.1,main = "Acelerometria (g)") %>% dyRangeSelector() %>%
  dyAxis("x", label = "tempo(s)")%>%
   dyAxis("y", label = "amplitude")

# Lendo o arquivo EDF
CHdr <- readEdfHeader("V16C1RCC92.edf") #leitura do cabeçalho
Signals <- readEdfSignals(CHdr) #leitura dos sinais

#criando vetor de tempo
tt = seq(from=0, to=1049, by=1) * 1/Signals$`Ch: 0-:G1.X`$sRate

df4 <- data.frame(time= tt, amp=Signals$`Ch: 1-:G1.Y`$signal) #criação de um dataframe para armazenamento dos dados
 dygraph(df4,main = "Acelerometria - Eixo Y (g)") %>% dyRangeSelector() %>%
  dyAxis("x", label = "tempo(s)")%>%
   dyAxis("y", label = "amplitude")
  
```

### Exercício 7

>A base de dados disponível na plataforma Moodle (ver figura abaixo) foi coletada utilizando-se o dispositivo TREMSEN (Precise Tremor Sensing), que é um dispositivo para a coleta de dados inerciais (i.e., movimentos).
A coleta de dados foi executada considerando os seguinte protocolo:
Um acelerômetro triaxial foi posicionado no dorso da mão, sobre o osso Capitato.
O eixo X do acelerômetro foi alinhado paralelamente à terceira falange distal.
Os dados foram coletados enquanto o participante realizava os seguintes movimentos: – 5 flexões do punho; – 5 extensões do punho; – 5 aduções do punho; – 5 abduções do punho.
Os dados coletados foram salvos no formato EDF e TXT, e nomeados de acordo com o tipo de movimento realizado (Adução, Flexão e Rotação).
Considerando as informações dadas, você deve:
a - Abrir o arquivo TXT no Excel e salvar uma versão deste arquivo no formato xls.
b - Salvar o arquivo xls gerado no formato csv.
c - Abrir o arquivo coletado em xls no R e gerar um gráfico utilizando a função qplot. Incluir legendas dos eixos x - tempo (s) e y - amplitude (g).
d - Abrir o arquivo coletado em csv no R e gerar um gráfico utilizando a função qplot. Incluir as legendas dos eixos x - tempo (s) e y - amplitude (g).
e - Abrir o arquivo coletado em edf no R e gerar um gráfico utilizando a função qplot. Incluir as legendas dos eixos x - tempo (s) e y - amplitude (g).
f - Incluir todos os resultados e códigos resultantes da execução desta sequência de passos na resposta desta questão.


```{R}
l1 <- read.xlsx("Aducao.xlsx",sheet = 1, skipEmptyRows = FALSE)
qplot(l1$`[Time]`, l1$`[G1.X]`) + labs(x = "tempo (s)", y="amplitude (g)")

l2 <- read.csv("Aducao.csv", header = TRUE, sep = ";")
l2.1 <- data.frame(time=l2[[1]], amp=l2$X.G1.X.)
qplot(l2.1$`time`, l2.1$`amp`) + labs(x = "tempo (s)", y="amplitude (g)")

chdr <- readEdfHeader("Aduccao.edf")
Signals <- readEdfSignals(chdr)

t3 = seq(from=0, to=449, by=1) * 1/Signals$`Ch: 0-:G1.X`$sRate

l4 <- data.frame(time= t3, amp=Signals$`Ch: 1-:G1.Y`$signal)

qplot(l4$`time`,l4$`amp`) + labs(x = "tempo (s)", y="amplitude (g)")
```
